_wandb:
    value:
        cli_version: 0.24.0
        e:
            krbyrh1iv5w425jwx48p4327y6u0cddb:
                args:
                    - --config
                    - experiments/configs/train_config_q4.yaml
                codePath: experiments/train.py
                codePathLocal: experiments/train.py
                cpu_count: 48
                cpu_count_logical: 96
                disk:
                    /:
                        total: "107307073536"
                        used: "9826078720"
                email: arjanvstav@gmail.com
                executable: /gpfs/home3/scur2377/MLOps_2026/.venv/bin/python
                git:
                    commit: 39cd7d48143692a9d011b6465de6e20a4b08648f
                    remote: git@github.com:Hugovveen/MLOps_2026.git
                host: int6.local.snellius.surf.nl
                memory:
                    total: "269550755840"
                os: Linux-5.14.0-570.76.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: /gpfs/home3/scur2377/MLOps_2026/experiments/train.py
                python: CPython 3.13.1
                root: /gpfs/home3/scur2377/MLOps_2026
                startedAt: "2026-01-20T21:57:57.473944Z"
                writerId: krbyrh1iv5w425jwx48p4327y6u0cddb
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
                - 16
            "4": 3.13.1
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
data:
    value:
        batch_size: 32
        data_path: ../data/pcam
        dataset_type: pcam
        input_shape:
            - 3
            - 96
            - 96
        num_workers: 0
        use_weighted_sampler: false
device:
    value: cpu
experiment_name:
    value: pcam_mlp_baseline
model:
    value:
        dropout_rate: 0.2
        hidden_units:
            - 64
            - 32
        input_shape:
            - 96
            - 96
            - 3
        num_classes: 2
seed:
    value: 42
training:
    value:
        epochs: 3
        learning_rate: 0.001
        save_dir: ./experiments/results
